### ISSUE TITLE
静态编译后出错

### ISSUE THREAD

**Issue by kookliu** [sanonz/hexo-theme-concise#18]
$ hexo g
INFO  Start processing
INFO  Files loaded in 111 ms
ERROR /Users/jialj/GitHub/jiazhe/themes/concise/layout/post.ejs:3
    1| <%- partial('_partial/article', {post: page, view: true}) %>
    2| 
 >> 3| <% if( theme.disqus.enable && page.comments ) { %>
    4| <%- partial('_partial/comments', {post: page}) %>
    5| <% } %>
    6| 

Cannot read property 'enable' of undefined
TypeError: /Users/jialj/GitHub/jiazhe/themes/concise/layout/post.ejs:3
    1| <%- partial('_partial/article', {post: page, view: true}) %>
    2| 
 >> 3| <% if( theme.disqus.enable && page.comments ) { %>
    4| <%- partial('_partial/comments', {post: page}) %>
    5| <% } %>
    6| 

Cannot read property 'enable' of undefined
    at eval (eval at compile (/Users/jialj/GitHub/jiazhe/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:12:25)
    at returnedFn (/Users/jialj/GitHub/jiazhe/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/jialj/GitHub/jiazhe/node_modules/hexo/lib/theme/view.js:124:48)
    at Theme._View.View.View.render (/Users/jialj/GitHub/jiazhe/node_modules/hexo/lib/theme/view.js:29:15)
    at route.set (/Users/jialj/GitHub/jiazhe/node_modules/hexo/lib/hexo/index.js:386:29)
    at tryCatcher (/Users/jialj/GitHub/jiazhe/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/jialj/GitHub/jiazhe/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/jialj/GitHub/jiazhe/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:449:10)
    at resume_ (_stream_readable.js:888:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by sanonz** [comment]
是不是第二步没做
https://github.com/sanonz/hexo-theme-concise#%E5%88%87%E6%8D%A2
